#!/bin/bash

#SBATCH --partition=gpu_shared_course
#SBATCH --gres=gpu:1
#SBATCH --job-name=Deterministic-Refinement
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=3
#SBATCH --time=24:00:00
#SBATCH --mem=32000M
#SBATCH --output=slurm_output_%A.out
#SBATCH --mail-type=ALL

module purge
module load 2021
module load Anaconda3/2021.05

# Activate your environment
source activate cgn-gpu

# Run your code
## runs all experiments to reproduce Table 3 and 4 in the paper
python imagenet_pipeline.py

